spring:
  profiles:
    active: mybatis,redis

dubbo:
  # 服务提供者名字
  application:
    name: article-service
    qosEnable: false
  # 注册中心
  registry:
    address: zookeeper://192.168.0.100:2181
  # 使用的协议
  protocol:
    name: dubbo
    port: 20881
  # 扫描服务提供包的service注解
  scan: org.polele.article