spring:
  datasource:
    url: jdbc:mysql://192.168.0.22:3306/blob?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: pyy
    password: pyy123
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # 指定需要别名的pojo包
  type-aliases-package: org.polele.pojo
  # mapper对应的xml文件
  mapper-locations: classpath:mapper/*.xml
  # mybatis配置
  config-location: classpath:mybatis/mybatis-config.xml
  # pojo所在需要创建表的包
#  model:
#    pack: org.polele.pojo.*
#  database:
#    type: mysql
#  #如何创建表
#  table:
#    auto: update